version: '3.5'

services:
  postgres:
    build:
      context: ./tests
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - postgres
    restart: unless-stopped

  reporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reporter
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DBNAME=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
      - APP_PORT=80
    ports:
      - 8080:80
    networks:
      - postgres

networks:
  postgres:
    driver: bridge