name: push
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
      
    - name: install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

    - name: golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run
      
    - name: install test tools
      run: go get github.com/ory/go-acc
    
    - name: run tests
      run: $(go env GOPATH)/bin/go-acc -o coverage.txt ./...

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
